### ISSUE TITLE
Disabling daemons not working again in v1.1.1

### ISSUE THREAD

**Issue by Mikasa-san** [c22dev/Geranium#13]
When Geranium disabling the daemons it sets disabled.plist to a weird access permissions and it should be 644 also it should be root:wheel otherwise it will not working

**Comment by c22dev** [comment]
Did it worked for you on past versions ? Haven't changed anything system wise since 1.1 or 1.0.4

**Comment by c22dev** [comment]
Tested on 2nd device and it just works...

**Comment by Mikasa-san** [comment]
nvm It works but seems like not every time
