### ISSUE TITLE
Option to enable/disable safe mode for cleaner

### ISSUE THREAD

**Issue by Nvdtn19** [c22dev/Geranium#14]
I accidentally switch off the safe mode cleaner for ios 15. Now some of my app doesn't have notification until I reboot the phone. I tried to uninstall and reinstall the geranium app and even wiping the data, but that doesn't let me turn on safe mode back. Even in the app settings. So in further version the app need to add this function, the current state is kinda inconveniences for me. But by the way, is there any way to turn on safe mode back by editing some files?

**Comment by c22dev** [comment]
Yeah it's possible. You need to find the app's container and enable the user default. 
It should be in var/mobile/Containers/Data/Application/<GUID, here look for geranium>/Library/Preferences/ and there should be a plist where you can edit the following Boolean : tmpClean

**Comment by c22dev** [comment]
And for the notification bug, we (a guy from an other issue and me) are looking on it.
For now the only solution is to reset your phone (wipe it) from settings...

**Comment by Nvdtn19** [comment]
> Yeah it's possible. You need to find the app's container and toggle the matching userdefault.
> There should be a plist in /var/mobile/Containers/Data/Application/<GUID, here look for geranium>/Library/Preferences/ and there should be a plist where you can edit the following Boolean : tmpClean
> Ig it should be true for you, make it false.

**Comment by Nvdtn19** [comment]
> Yeah it's possible. You need to find the app's container and toggle the matching userdefault.
> There should be a plist in /var/mobile/Containers/Data/Application/<GUID, here look for geranium>/Library/Preferences/ and there should be a plist where you can edit the following Boolean : tmpClean
> Ig it should be true for you, make it false.

How do I find that plist file? I looked into the said directory in Filza but there isn't any plist there

**Comment by c22dev** [comment]
Contact me on Discord (`c22dev`), I'll send you an beta build containing the option to disable/enable safe mode.

**Comment by c22dev** [comment]
1.1.2 is out and should provide a fix for every of the issues/suggestions you mentioned !
