### ISSUE TITLE
Enable screen time feature crashes app

### ISSUE THREAD

**Issue by Thyssenkrupp234** [c22dev/Geranium#16]
{"app_name":"Geranium","timestamp":"2024-02-13 10:28:36.00 -0800","app_version":"1.1.1","slice_uuid":"b7122b77-45c8-323f-a109-9a6a74dac406","build_version":"1","platform":2,"bundleID":"live.cclerc.geranium","share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"iPhone OS 16.1 (20B82)","roots_installed":0,"name":"Geranium","incident_id":"1B9302C5-C8E8-4FE0-B4D2-55AC9194E4F1"}
{
  "uptime" : 190,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone10,4",
  "coalitionID" : 428,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.1",
    "releaseType" : "User",
    "build" : "20B82"
  },
  "captureTime" : "2024-02-13 10:28:35.5516 -0800",
  "incident" : "1B9302C5-C8E8-4FE0-B4D2-55AC9194E4F1",
  "pid" : 7714,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-02-13 10:28:30.5353 -0800",
  "procStartAbsTime" : 4618589561,
  "procExitAbsTime" : 4738831839,
  "procName" : "Geranium",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/512EB020-38C1-4D44-AE53-6B99D1FB3622\/Geranium.app\/Geranium",
  "bundleInfo" : {"CFBundleShortVersionString":"1.1.1","CFBundleVersion":"1","CFBundleIdentifier":"live.cclerc.geranium"},
  "storeInfo" : {"deviceIdentifierForVendor":"00B204DA-79BE-44C1-BF82-8A7CC430D69B"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "live.cclerc.geranium",
  "crashReporterKey" : "343778e6eac241c3e5de5a03bbb23b90949ebd13",
  "basebandVersion" : "5.03.01",
  "exception" : {"codes":"0x0000000000000001, 0x0000000187e58240","rawCodes":[1,6574932544],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":7714},
  "os_fault" : {"process":"Geranium"},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":14155,"threadState":{"x":[{"value":10781742176},{"value":0},{"value":18446744073709551584},{"value":10781742176},{"value":10781742272},{"value":6168927040},{"value":101},{"value":0},{"value":204},{"value":203},{"value":5200},{"value":2043},{"value":4150290523},{"value":2045},{"value":4152389698},{"value":4150290523},{"value":66},{"value":2004877312},{"value":0},{"value":5746269184},{"value":3221225472},{"value":10745288464},{"value":1},{"value":10745222112},{"value":5746269184},{"value":5754665472},{"value":5746269184},{"value":10767260480},{"value":1}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6574932544},"cpsr":{"value":1610612736},"fp":{"value":6168927216},"sp":{"value":6168927184},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6574932544,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":197184,"symbol":"closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:)","symbolLocation":356,"imageIndex":0},{"imageOffset":197184,"symbol":"closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:)","symbolLocation":356,"imageIndex":0},{"imageOffset":196520,"symbol":"closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:)","symbolLocation":192,"imageIndex":0},{"imageOffset":194932,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":228,"imageIndex":0},{"imageOffset":851688,"symbol":"doStuff()","symbolLocation":988,"imageIndex":1},{"imageOffset":848968,"symbol":"enableBack()","symbolLocation":1000,"imageIndex":1},{"imageOffset":618836,"symbol":"closure #1 in closure #3 in closure #1 in ByeTimeView.body.getter","symbolLocation":28,"imageIndex":1},{"imageOffset":312624,"symbol":"closure #3 in closure #1 in UIApplication.confirmAlert(title:body:onOK:noCancel:onCancel:yes:)","symbolLocation":88,"imageIndex":1},{"imageOffset":309092,"symbol":"thunk for @escaping @callee_guaranteed (@guaranteed UIAlertAction) -> ()","symbolLocation":64,"imageIndex":1},{"imageOffset":4166304,"symbol":"-[UIAlertController _invokeHandlersForAction:]","symbolLocation":80,"imageIndex":2},{"imageOffset":5695628,"symbol":"__103-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:dismissCompletion:]_block_invoke_2","symbolLocation":28,"imageIndex":2},{"imageOffset":2483080,"symbol":"-[UIPresentationController transitionDidFinish:]","symbolLocation":1076,"imageIndex":2},{"imageOffset":7331204,"symbol":"__56-[UIPresentationController runTransitionForCurrentState]_block_invoke.88","symbolLocation":300,"imageIndex":2},{"imageOffset":2710448,"symbol":"-[_UIViewControllerTransitionContext completeTransition:]","symbolLocation":104,"imageIndex":2},{"imageOffset":15939656,"symbol":"__UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__","symbolLocation":28,"imageIndex":2},{"imageOffset":817364,"symbol":"-[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]","symbolLocation":604,"imageIndex":2},{"imageOffset":813192,"symbol":"-[UIViewAnimationState sendDelegateAnimationDidStop:finished:]","symbolLocation":212,"imageIndex":2},{"imageOffset":811160,"symbol":"-[UIViewAnimationState animationDidStop:finished:]","symbolLocation":192,"imageIndex":2},{"imageOffset":811416,"symbol":"-[UIViewAnimationState animationDidStop:finished:]","symbolLocation":448,"imageIndex":2},{"imageOffset":74076,"symbol":"CA::Layer::run_animation_callbacks(void*)","symbolLocation":228,"imageIndex":3},{"imageOffset":411592,"symbol":"_dispatch_client_callout","symbolLocation":16,"imageIndex":4},{"imageOffset":286488,"symbol":"_dispatch_main_queue_drain","symbolLocation":888,"imageIndex":4},{"imageOffset":285584,"symbol":"_dispatch_main_queue_callback_4CF$VARIANT$armv81","symbolLocation":36,"imageIndex":4},{"imageOffset":604232,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":12,"imageIndex":5},{"imageOffset":488660,"symbol":"__CFRunLoopRun","symbolLocation":2096,"imageIndex":5},{"imageOffset":506748,"symbol":"CFRunLoopRunSpecific","symbolLocation":584,"imageIndex":5},{"imageOffset":6532,"symbol":"GSEventRunModal","symbolLocation":160,"imageIndex":6},{"imageOffset":3625928,"symbol":"-[UIApplication _run]","symbolLocation":868,"imageIndex":2},{"imageOffset":3625024,"symbol":"UIApplicationMain","symbolLocation":312,"imageIndex":2},{"imageOffset":1649764,"imageIndex":7},{"imageOffset":1087104,"imageIndex":7},{"imageOffset":1007484,"imageIndex":7},{"imageOffset":681560,"symbol":"static GeraniumApp.$main()","symbolLocation":40,"imageIndex":1},{"imageOffset":701388,"symbol":"main","symbolLocation":12,"imageIndex":1},{"imageOffset":81392,"symbol":"start","symbolLocation":2096,"imageIndex":8}]},{"id":14156,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14157,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14158,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14159,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":4500,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":10},{"imageOffset":76296,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":10},{"imageOffset":76868,"symbol":"mach_msg_overwrite","symbolLocation":384,"imageIndex":10},{"imageOffset":5768,"symbol":"mach_msg","symbolLocation":20,"imageIndex":10},{"imageOffset":483268,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":156,"imageIndex":5},{"imageOffset":487796,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":506748,"symbol":"CFRunLoopRunSpecific","symbolLocation":584,"imageIndex":5},{"imageOffset":255016,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":208,"imageIndex":11},{"imageOffset":254756,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":60,"imageIndex":11},{"imageOffset":4825312,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":424,"imageIndex":2},{"imageOffset":352116,"symbol":"__NSThread__start__","symbolLocation":704,"imageIndex":11},{"imageOffset":12384,"symbol":"_pthread_start","symbolLocation":116,"imageIndex":9},{"imageOffset":5768,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":14160,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14161,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14162,"frames":[{"imageOffset":5748,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":14164,"name":"com.apple.SwiftUI.AsyncRenderer","frames":[{"imageOffset":4500,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":10},{"imageOffset":76296,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":10},{"imageOffset":76868,"symbol":"mach_msg_overwrite","symbolLocation":384,"imageIndex":10},{"imageOffset":5768,"symbol":"mach_msg","symbolLocation":20,"imageIndex":10},{"imageOffset":483268,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":156,"imageIndex":5},{"imageOffset":487796,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":506748,"symbol":"CFRunLoopRunSpecific","symbolLocation":584,"imageIndex":5},{"imageOffset":255016,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":208,"imageIndex":11},{"imageOffset":254676,"symbol":"-[NSRunLoop(NSRunLoop) run]","symbolLocation":60,"imageIndex":11},{"imageOffset":607740,"imageIndex":7},{"imageOffset":601340,"imageIndex":7},{"imageOffset":352116,"symbol":"__NSThread__start__","symbolLocation":704,"imageIndex":11},{"imageOffset":12384,"symbol":"_pthread_start","symbolLocation":116,"imageIndex":9},{"imageOffset":5768,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6574735360,
    "size" : 4812800,
    "uuid" : "bd77c4a0-5cef-3edd-9381-465818f7ae9b",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4297949184,
    "size" : 1163264,
    "uuid" : "b7122b77-45c8-323f-a109-9a6a74dac406",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/512EB020-38C1-4D44-AE53-6B99D1FB3622\/Geranium.app\/Geranium",
    "name" : "Geranium"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6709616640,
    "size" : 23920640,
    "uuid" : "aa0a89bd-e48f-31db-ad5c-5c724ce77d12",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6698188800,
    "size" : 3346432,
    "uuid" : "564fd4f3-2f8c-351f-904f-0e562d7dfc8c",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/QuartzCore",
    "name" : "QuartzCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6790717440,
    "size" : 540672,
    "uuid" : "19f4cd59-ab92-3ed4-9730-174fa4b1468e",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6592765952,
    "size" : 3985408,
    "uuid" : "a68fce15-6c1a-38c6-9ed3-7063272d237e",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7570046976,
    "size" : 36864,
    "uuid" : "259d3407-93ef-31ed-8b56-b271d17e4e55",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6733537280,
    "size" : 22839296,
    "uuid" : "579229a0-9abb-35a3-8104-3f567c142dd8",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7157420032,
    "size" : 499612,
    "uuid" : "a2aa3a68-07f7-3d52-a49e-d29d136813f3",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7875858432,
    "size" : 69632,
    "uuid" : "0f4eb363-5df3-30d4-95d2-3ada3d3e82f2",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7626657792,
    "size" : 221168,
    "uuid" : "7798d964-d97e-320b-99a2-95b63e0f882b",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6579748864,
    "size" : 9093120,
    "uuid" : "6ab9faeb-6a5f-393e-9e76-22016fdc6129",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  }
],
  "sharedCache" : {
  "base" : 6562938880,
  "size" : 2741108736,
  "uuid" : "540181a3-d4e1-3457-8471-fad06b886c22"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=790.3M resident=0K(0%) swapped_out_or_unallocated=790.3M(100%)\nWritable regions: Total=604.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=604.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                     704K        3 \nColorSync                           80K        5 \nCoreAnimation                     1616K       70 \nFoundation                          16K        1 \nImage IO                           400K        4 \nKernel Alloc Once                   32K        1 \nMALLOC                           591.9M      174 \nMALLOC guard page                  128K        8 \nSQLite page cache                  256K        2 \nSTACK GUARD                        144K        9 \nStack                             5360K        9 \nVM_ALLOCATE                       3232K        4 \n__CTF                               756        1 \n__DATA                            10.7M      473 \n__DATA_CONST                      48.5M      492 \n__DATA_DIRTY                      2571K      400 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       304.9M        3 \n__LLVM_COV                          48K        1 \n__OBJC_RO                         78.4M        1 \n__OBJC_RW                         2427K        1 \n__TEXT                           485.4M      498 \ndyld private memory                256K        1 \nmapped file                      173.8M       16 \nshared memory                     2096K        5 \n===========                     =======  ======= \nTOTAL                              1.7G     2184 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "65287aa4be905e686a05f0a2"
      },
      "deploymentId" : 240000079
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by c22dev** [comment]
Mmh...
It fails at the function in charge of removing the ScreenTime.
I'll look into it and eventually send you debug build

**Comment by Thyssenkrupp234** [comment]
Thanks! fyi, removing screen time works

**Comment by c22dev** [comment]
Oh okay so it's only enabling back ! Thanks for specifying...

**Comment by c22dev** [comment]
<img width="514" alt="Capture d’écran 2024-02-22 à 16 21 27" src="https://github.com/c22dev/Geranium/assets/102235607/95f0599c-8f1b-4839-b222-ca61ce1e02a3">
Found the issue !
The app doesn't check if the plist doesn't exist, and some issue might happen with that if there's a problem with permissions.
Will fix that soon !!

**Comment by c22dev** [comment]
This should be fixed in 1.1.2, lmk if it works for you.
