### ISSUE TITLE
Can it add a feature to hook CNCopyCurrentNetworkInfo to custom some app to get BSSID and SSID Info?

### ISSUE THREAD

**Issue by wintelsui** [c22dev/Geranium#18]
Can it add a feature to hook CNCopyCurrentNetworkInfo to custom some app to get BSSID and SSID Info?

**Comment by wintelsui** [comment]
uh-huh, I just think that simulate location and simulate wifi are a couple, May be I need try it by myself, I need learn how to use theos now.

**Comment by c22dev** [comment]
You can't really simulate WiFi's IP position without a VPN, the IP is attributed by your rooter and doesn't have a link with your phone, if that's what you meant

**Comment by c22dev** [comment]
Shall I close this ?
