### ISSUE TITLE
Cant bookmark LocSim Locations via share menu

### ISSUE THREAD

**Issue by MMJv3** [c22dev/Geranium#22]
Opening apple maps and opening the share map to bookmark a location, the pop up appears to give it a name but does not actually bookmark it

14 Pro
16.5.1

**Comment by c22dev** [comment]
Weird. You are using latest ?

**Comment by MMJv3** [comment]
on latest when i made this, reinstalling didn’t help, not sure what i can provide to help you understand the problem but let me know

**Comment by c22dev** [comment]
I can't really reproduce...
I'll ask someone on 16.5.1.
Btw, are you using Apple Maps ? Have you tried uninstalling it and uninstalling it back ?
Could you also try using 1.1.1 and see if it works on there ?
thanks.

**Comment by c22dev** [comment]
Does the Bookmark location in geranium slider (sheet) go down ?

**Comment by MMJv3** [comment]
Not sure what this means but this is step by step EXACTLY what happens

Open apple maps

Click location or search something

Location comes up, directions begin button and all

Click share upper right next to X button

Click bookmark in geranium

geranium bookmark set name screen appears

pick name press OK button

open geranium and go to bookmarks upper right

it will not be there

**Comment by c22dev** [comment]
I mean it works for me, reproduced word by word what you meant.
My question is when pressing OK, do you get back to share menu ? Or it hangs ?

**Comment by MMJv3** [comment]
It goes back to the menu that has the share button in the upper right

Honestly not sure what i can do to help you figure out the issue

This isn’t really the biggest deal for me but i thought i’d make in issue in case someone else had the same problem

**Comment by c22dev** [comment]
Thanks for reporting anyway.
Could you try sending me the app's preferences (we'll see if it at least store)
Go in /var/mobile/Containers/Data/Application/
here look for geranium
Go in Geranium
And send me all the files in Preferences.

**Comment by MMJv3** [comment]
That preferences folder doesn’t exist in the specified path. 

Documents
Library
System Data
tmp
.plist file

**Comment by c22dev** [comment]
Okay, my bad. It should be in Library/Preferences then (ig)
