### ISSUE TITLE
I hope it can be fully Chineseized.

### ISSUE THREAD

**Issue by vsvjv** [c22dev/Geranium#28]
First of all, I am very grateful to c22dev for making this app. This app is very easy to use, but there are many functions that I have not tried yet because this software has too much English. I hope that one day it will be updated with a fully Chinese version.The above feedback is all edited through translation.

**Comment by c22dev** [comment]
Hi there, and welcome. The following text will be written using a translator so you don't have to translate back.

我将很快联系负责中文翻译的人员，看看我们是否可以进行更新。顺便说一下，如果你认识会说中英文的人，并且有时间进行翻译，他们可以联系我：constantin@cclerc.ch

对造成的不便感到抱歉，感谢你使用这个应用程序！
