### ISSUE TITLE
i'm new to jailbreaking, ios 15 using dopamine and sileo on iphone x [CONT. IN POST]

### ISSUE THREAD

**Issue by 15ggd** [c22dev/Geranium#31]
i'm new to jailbreaking, ios 15 using dopamine and sileo on iphone x which used to be my brothers, current phone and ipad gen 9 is on ios 17, can't downgrade so i pulled out my brothers old iphone x, which was easily jailbreaked using dopamine (sideloadly) to then download trollstore, the account has screentime and login restrictions and i am trying to remove these restrictions without doing anything on my brother's current device, ByeTime did not work

**Comment by c22dev** [comment]
Any specific thing ? Did it crash ? Did you restarted as prompted ? What daemond did you choose in-app ? Did you use any other method/app ?

**Comment by 15ggd** [comment]
the app did not work, i do not know what a daemon is, i just enabled byetime then restarted my iphone and it did not remove screentime at all
