### ISSUE TITLE
can’t enter latitude or longitude 

### ISSUE THREAD

**Issue by alibiiiiiiiiiiiiiiiiii** [c22dev/Geranium#32]
Whenever I click on the pin, it simply tells me enter your coordinates, i click okay then it tells me “those coordinates are empty” never giving me the regular prompt to enter them. I have geranium on my other iPhone & it works fine? Why is this
![5901615D-02F8-4140-BFB5-47F0421138F5](https://github.com/user-attachments/assets/5accddd6-f13b-4550-806d-6421dcb4d4b1)

**Comment by c22dev** [comment]
This is a known issue and will be fixed soon. My guess is that you are using iOS 15 right ?

**Comment by alibiiiiiiiiiiiiiiiiii** [comment]
> This is a known issue and will be fixed soon. My guess is that you are using iOS 15 right ?

Yes, 15.8.1

**Comment by alibiiiiiiiiiiiiiiiiii** [comment]
Ummmm how do I fix?

**Comment by c22dev** [comment]
Well you can't fix it. 
it's a big with iOS 15. will bring a fix sooner or later.
