### ISSUE TITLE
When i press my location wont change 

### ISSUE THREAD

**Issue by Peakxz** [c22dev/Geranium#33]
When i press my location wont change i don’t know why

**Comment by c22dev** [comment]
Hi there, thanks for opening this issue.
What version are you on?

**Comment by c22dev** [comment]
Sorry, I meant your iOS version

**Comment by Peakxz** [comment]
18

**Comment by Peakxz** [comment]
18.0

**Comment by c22dev** [comment]
Oh, well Geranium isn't supported on your device. You should have gotten a warning.
