### ISSUE TITLE
Save coordinates from maps doesnt work

### ISSUE THREAD

**Issue by vasilisthh** [c22dev/Geranium#35]
So when you add a pin in maps and then you click save in Geranium, it asks you to give a name and when you click save it doesnt save the bookmark.

**Comment by c22dev** [comment]
Hi there, thanks for opening this issue!
May I know what iOS version you are on ? Thanks a bunch
From my testing it worked, but it's not the first time I see this issue. I will try to bring a fix.

**Comment by vasilisthh** [comment]
iPhone X, palra1n
16.7.8

**Comment by oldman20** [comment]
same on ipad mini 5 Trollstore, ios 17
