### ISSUE TITLE
I have a translation Hebrew for Geranium

### ISSUE THREAD

**Issue by Korel2000** [c22dev/Geranium#38]

**Comment by c22dev** [comment]
nice, please open a pull request

**Comment by Korel2000** [comment]
How do you do that?
Is it possible to email you?

השג את Outlook עבור iOS<https://aka.ms/o0ukef>
________________________________
מאת: c22dev ***@***.***>
‏‏נשלח: Thursday, September 19, 2024 9:24:12 AM
‏‏אל: c22dev/Geranium ***@***.***>
עותק: Korel ***@***.***>; Author ***@***.***>
‏‏נושא: Re: [c22dev/Geranium] I have a translation Hebrew for Geranium (Issue #38)


nice, please open a pull request

**Comment by c22dev** [comment]
You go into the project's Github, you fork it, you make your changes to the Localizable file, then you open a pull request by going into the pull request tab !
Yes, of course ! You can email me message@cclerc.ch.

**Comment by Korel2000** [comment]
Thank you

השג את Outlook עבור iOS<https://aka.ms/o0ukef>
________________________________
מאת: c22dev ***@***.***>
‏‏נשלח: Thursday, September 19, 2024 9:42:03 AM
‏‏אל: c22dev/Geranium ***@***.***>
עותק: Korel ***@***.***>; Author ***@***.***>
‏‏נושא: Re: [c22dev/Geranium] I have a translation Hebrew for Geranium (Issue #38)


You go into the project's Github, you fork it, you make your changes to the Localizable file, then you open a pull request by going into the pull request tab !
Yes, of course ! You can email me ***@***.******@***.***>.
