### ISSUE TITLE
Daemon List on Top of Bottom Bar

### ISSUE THREAD

**Issue by ImLogueybear** [c22dev/Geranium#4]
iOS Version: 16.4.1 
Geranium Version: 1.0.3
TrollStore Version: 2.0.11

After launching the app and selecting the “Daemons” tab, the list of all daemons will display and visually overlay on top  of the bottom navigation bar. The navigation bar is selectable. Closing and relaunching the app does not correct the issue. 

![IMG_4012](https://github.com/c22dev/Geranium/assets/59677000/c97a7966-2487-4041-8230-fb09cfbf70cb)

**Comment by c22dev** [comment]
This is a known issue, thanks anyway for reporting. Still waiting for an answer on this sub :
https://www.reddit.com/r/SwiftUI/comments/190ry1v/swiftui_list_visible_behind_tabview/

**Comment by c22dev** [comment]
Should have fixed it with latest commit.
<img width="396" alt="Capture d’écran 2024-01-21 à 15 28 00" src="https://github.com/c22dev/Geranium/assets/102235607/dbb7d31d-6c8e-4546-af3e-56302a6fc803">
