### ISSUE TITLE
CySxL is a Taiwanese 🇹🇼 shouldn't be labeled with a Chinese flag

### ISSUE THREAD

**Issue by olivertzeng** [c22dev/Geranium#6]
![image](https://github.com/c22dev/Geranium/assets/86348833/397539f0-7dcb-4191-ae82-5f3f2672e837)

**Comment by c22dev** [comment]
I will fix this next release. I am really sorry for the issue...

**Comment by c22dev** [comment]
Fixed in [this commit](https://github.com/c22dev/Geranium/commit/d495c4bbba50a340c9e8d7b300b10f977694c287).

**Comment by olivertzeng** [comment]
Thanks!
