### ISSUE TITLE
iPhone 12 iOS 15.5 (A14) - "Daemons" UI bug

### ISSUE THREAD

**Issue by Cyosai** [c22dev/Geranium#8]
![image](https://github.com/c22dev/Geranium/assets/114384049/23ba3615-5dc0-40bf-84bb-8dd2562e0864)

**Comment by Cyosai** [comment]
![Uploading 4A3C6D71-C031-4F9D-826D-C29427B8EFBD.png…]()

**Comment by Cyosai** [comment]
![Uploading 887F5E60-0641-4988-A9AB-C47CADA4C7BA.png…]()

**Comment by Cyosai** [comment]
https://github.com/c22dev/Geranium/assets/114384049/76c0e255-c304-49d5-9ef5-d6cc8701e2c8

**Comment by c22dev** [comment]
Weird, I will try to debug this in simulator.

**Comment by c22dev** [comment]
Will be fixed next release. You will have to pull the list up to show the search bar (like in iOS Settings for instance).
This doesn't affect other devices, and even improve them.
<img width="813" alt="Capture d’écran 2024-01-21 à 15 06 14" src="https://github.com/c22dev/Geranium/assets/102235607/b36ca14e-9a29-4ee4-9f0f-72bb96bd341d">

**Comment by Cyosai** [comment]
Thanks so much!
